version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentd
    volumes:
    - /var/lib/docker/containers:/fluentd/log/containers # Example: Reading docker logs
    - ./file-mock:/fluentd/log/files/ #Example: Reading logs from a file
    - ./configurations:/fluentd/etc/
    - ./logs:/output/ # Example: Fluentd will collect logs and store it here for demo
    logging:
      driver: "local"
    ports:
      - 9880:9880

  # This app writes logs to a local file
  file-myapp:
    container_name: file-mock-myapp
    image: alpine
    volumes:
    - ./file-mock:/app
    command: [ /bin/sh , -c , "chmod +x /app/app.sh && ./app/app.sh"]
